Added some checks in the preprocess script

diff --git a/preprocess b/preprocess
--- a/preprocess
+++ b/preprocess
@@ -1,7 +1,28 @@
 #!/bin/bash
 
 FILE_NAME="$1"
+# Checking that filename argument is provided
+if [[ -z "$FILE_NAME" ]]; then
+    echo "Usage: $0 <file_name>" >&2
+    exit 1
+fi
+# Check that the given file exists
+if [[ ! -f "$FILE_NAME" ]]; then
+    echo "Error: File '$FILE_NAME' not found." >&2
+    exit 1
+fi
 
+# Check wether file is readable or not
+if [[ ! -r "$FILE_NAME" ]]; then
+    echo "Error: File '$FILE_NAME' is not readable." >&2
+    exit 1
+fi
+
+# Check that file is filled with the content
+if [[ ! -s "$FILE_NAME" ]]; then
+    echo "Error: File '$FILE_NAME' is empty." >&2
+    exit 1
+fi
 # Find the max ID
 maximum_id=$(awk -F';' 'NR > 1 && $1 ~ /^[0-9]+$/ && $1 > max { max = $1 } END { print max+0 }' "$FILE_NAME")
 made_up_id=$((maximum_id + 1))
